openapi: 3.0.0
info:
  version: 1.0.0
  title: Actor list
  description: >-
    This is an OpenAPI Specification created by oas-wizard
    (https://github.com/pafmon/oas-wizard)  
  contact:
    name: PabloFM
    email: pablofm@us.es
    url: 'http://www.isa.us.es'
  license:
    name: MIT
    url: 'http: //opensource.org/licenses/MIT'
paths:
  /api/v1/actors:
    get:
      description: Returns all actors
      operationId: getActors
      responses:
        '200':
          description: Actor List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/actor'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    post:
      description: Creates a new actor
      operationId: addActor
      responses:
        '201':
          description: actor created
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: actor
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/actor'
        description: Actor to be created
        required: true
  '/api/v1/actors/{email}':
    get:
      description: Returns a actor by email
      operationId: findActorByemail
      parameters:
        - name: email
          in: path
          description: email of actor to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Actor returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/actor'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    delete:
      description: deletes a single actor based on the email
      operationId: deleteActor
      parameters:
        - name: email
          in: path
          description: ID of actor to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: actor deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    put:
      description: Update a actor based on its email
      operationId: updateActor
      parameters:
        - name: email
          in: path
          description: ID of actor to put
          required: true
          schema:
            type: string
      responses:
        '204':
          description: actor updated
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: actor
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/actor'
        description: Actor to be updated
        required: true
components:
  schemas:
    errorModel:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    actor:
      description: ''
      type: object
      properties:
        name:
          type: string
          minLength: 1
        surname:
          type: string
          minLength: 1
        email:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
        phone:
          type: string
          minLength: 1
        address:
          type: string
          minLength: 1
        role:
          type: string
          minLength: 1
        created:
          type: string
          minLength: 1
      required:
        - name
        - surname
        - email
        - password
        - phone
        - address
        - role
        - created
